global:
  scrape_interval: 15s # How frequently to scrape targets
  evaluation_interval: 15s # How frequently to evaluate rules

scrape_configs:
  - job_name: 'sample-digitalnotice' # Name of the job
    static_configs:
      - targets: ['localhost:5267', 'sample-digitalnotice'] # The target endpoints to scrape metrics from
